### ISSUE TITLE
for training imagenet, how to train in multiple machines with same gpu numbers?

### ISSUE THREAD

**Issue by jeannotes** [libffcv/ffcv-imagenet#3]
when train imagenet, if we have 4 machines with same number of gous, how to train imagenet, any instructions?

thanks!

**Comment by lengstrom** [comment]
Hi, multi-node training is not officially supported. You could modify the script to work with multi node training by changing how the `rank` property is set (see where we call `dist.init_process_group`) and by setting the `address`, `port`, and `world_size` in the `dist` config category.
