### ISSUE TITLE
ImportError: libopencv_imgproc.so

### ISSUE THREAD

**Issue by eldarkurtic** [libffcv/ffcv-imagenet#7]
Hi,
After downgrading torch (and torchvision) version from 1.10 to 1.9, the `import ffcv` command raises `ImportError`:
``` 
File "/my_home/miniconda3/envs/test/lib/python3.9/site-packages/ffcv/libffcv.py", line 5, in <module>
    import ffcv._libffcv
ImportError: libopencv_imgproc.so.405: cannot open shared object file: No such file or directory
```

To reproduce:
```
conda create -y -n test python=3.9 cupy pkg-config compilers libjpeg-turbo opencv pytorch torchvision cudatoolkit=11.3 numba -c pytorch -c conda-forge
conda activate test
pip install ffcv
```
Running python and importing ffcv works fine at this point. But if we try to reinstall pytorch for 1.9 version with:
```
conda install pytorch==1.9.0 torchvision==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge
```
the `import ffcv` command breaks. Reinstalling ffcv doesn't help.

Do you have an idea how to resolve this? 
(installing 1.9 from the beginning works fine and doesn't break ffcv, but I guess that shouldn't be the preferred way of solving this issue)

**Comment by matanat** [comment]
Hi @eldarkurtic, have you been able to figure this out? 
What do you mean by "installing 1.9 from the beginning works fine"? Which steps did you use?

Thanks!

**Comment by eldarkurtic** [comment]
Hi @matanat !
Unfortunately I haven't been able to resolve the issue, and gave up in the end. 

"installing 1.9 from the beginning works fine": the only way I could get this up and running without the mentioned issues is by creating the entire conda environment from scratch with the 1.9 pytorch version. So, create a new fresh env, install the "correct" pytorch version and then `pip install ffcv`.

**Comment by giangnguyen2412** [comment]
Hi @eldarkurtic , running ```conda install -c conda-forge opencv``` solved my same problem.

**Comment by eldarkurtic** [comment]
@giangnguyen2412 thanks a lot for the suggestion!
